theme = ""
languageCode = "cz-cs"
baseurl = "https://www.glowofamber.cz/"
title = "Glow of Amber"

author = "Markéta Neradová"
copyright = "Copyright © 2019, Markéta Neradová, all rights reserved."

# Code higlighting settings
pygmentsCodefences = true
pygmentsStyle = "vs"

# Do not pluralize site sections
pluralizelisttitles = false

[params]
    name = "Glow of Amber"
    description = "Chovatelka psů."

    favicon = "/favicon.svg"
    backgroundImage = "/background.png"
    logo = "/logo.svg"
