theme = "hugo-theme-tailwindcss-starter"
languageCode = "cz-cs"
baseurl = "/"
title = "Glow of Amber"

author = "Markéta Neradová"
copyright = "Copyright © 2019, Markéta Neradová, all rights reserved."

# Code higlighting settings
pygmentsCodefences = true
pygmentsStyle = "vs"

[params]
    name = "Glow of Amber"
    description = "Chovatelka psů."

    favicon = "/favicon.svg"
    backgroundImage = "/background.png"
    logo = "/logo.svg"
