# theme = ""
languageCode = "cz-cs"
baseurl = "https://www.glowofamber.cz/"
title = "Glow of Amber"

author = "Markéta Neradová"
copyright = "Copyright © 2019 - 2021, Markéta Neradová, all rights reserved."

# Do not pluralize site sections
pluralizelisttitles = false

[permalinks]
   tags = "/novinky/:slug/"

[params]
    name = "Glow of Amber"
    description = "CHS border kolii."

    favicon = "/favicon.svg"
    backgroundImage = "/background.png"
    logo = "/logo.svg"

# https://github.com/dirkolbrich/hugo-theme-tailwindcss-starter
[build]
  writeStats = true
