[build.environment]
  YARN_VERSION = "1.22.10"
  NPM_VERSION = "7.6.3"
  HUGO_VERSION = "0.81.0"

[context.production.environment]
  HUGO_VERSION = "0.81.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[build]
  command = "npm install -g postcss-cli && npm install -g autoprefixer && npm install && hugo --gc --minify"
  publish = "public"

# [context.deploy-preview]
#   command = "./themes/hugo-theme-tailwindcss-starter/npm build:preview"
