[build.environment]
  YARN_VERSION = "1.12.1"
  NPM_VERSION = "6.4.1"
  HUGO_VERSION = "0.55.6"

[build]
  command = "mkdir dist && cd themes/hugo-theme-tailwindcss-starter && npm install -g postcss-cli && npm install -g autoprefixer && npm install && cd ../.."
  publish = "dist"

# [context.deploy-preview]
#   command = "./themes/hugo-theme-tailwindcss-starter/npm build:preview"
