[build.environment]
  YARN_VERSION = "1.12.1"
  NPM_VERSION = "6.4.1"
  HUGO_VERSION = "0.55.6"

[build]
  command = "cd themes/hugo-theme-tailwindcss-starter && npm install postcss-cli && yarn build && ../.."
  publish = "dist"

[context.deploy-preview]
  command = "./themes/hugo-theme-tailwindcss-starter/yarn build:preview"
