backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow
media_folder: "static/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/uploads/" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - label: "Novinky" # Used in the UI
    name: "novinky" # Used in routes, e.g., /admin/collections/blog
    folder: "content/novinky" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Nadpis", name: "title", widget: "string"}
      - {label: "Datum", name: "date", widget: date}
      - {label: "Rok", name: "tags", widget: "select", options: ["2018", "2019", "2020"], default: "2020"}
      - {label: "Obrázek", name: "image", widget: image}
      - {label: "Obsah", name: "body", widget: "markdown"}
  - label: "Stránky"
    name: "pages"
    files:
      - label: "Hlavní stránka"
        name: "index"
        file: "content/_index.md"
        fields:
          - {label: Nadpis, name: title, widget: string}
          - {label: "Obsah", name: "body", widget: "markdown"}
